### ISSUE TITLE
Block support

### ISSUE THREAD

**Issue by Secret-chest** [Secret-chest/scratch2python#8]
Support Scratch blocks. More will be added when these are about to be finished.

Note: Rotation is rendered but blocks using it are not supported, so no linked issue.

- [x] when flag clicked
- [x] set x/y
- [x] change x/y
- [x] go to x, y
- [ ] x position (nneds #5)
- [ ] y position (needs #5)
- [ ] point in direction
- [ ] point towards mouse
- [ ] point towards sprite
- [ ] turn left
- [ ] turn right
- [ ] direction (needs #5)
- [x] go to mouse
- [ ] mouse x (needs #5)
- [ ] mouse y (needs #5)
- [x] wait seconds
- [ ] wait until
- [ ] go to sprite
- [ ] when key pressed (needs #7)
- [ ] key pressed? (needs #7, #5)
- [ ] if then
- [ ] if then else
- [ ] repeat until
- [ ] repeat
- [x] forever
- [ ] set size
- [ ] change size
- [ ] variable (needs #5, #6)
- [ ] set variable (needs #6)
- [ ] change variable (needs #6)
- [ ] touching? (needs #5)
- [ ] touching color? (needs #5)
- [ ] equals (needs #5)
- [ ] greater than (needs #5)
- [ ] less than (needs #5)
- [ ] + (needs #5)
- [ ] - (needs #5)
- [ ] * (needs #5)
- [ ] / (needs #5)
- [ ] mod (needs #5)
